--------------------------------------------------------
--  File created - wtorek-maja-11-2021   
--------------------------------------------------------
DROP TABLE "C##SUVRES"."CATHEDRAL" cascade constraints;
DROP TABLE "C##SUVRES"."CLASSES" cascade constraints;
DROP TABLE "C##SUVRES"."EMPLOYEE" cascade constraints;
DROP TABLE "C##SUVRES"."FACULTY" cascade constraints;
DROP TABLE "C##SUVRES"."MARK" cascade constraints;
DROP TABLE "C##SUVRES"."POSITION" cascade constraints;
DROP TABLE "C##SUVRES"."STUDENT" cascade constraints;
DROP TABLE "C##SUVRES"."STUDENT_WORK_GROUP" cascade constraints;
DROP TABLE "C##SUVRES"."SUBJECT" cascade constraints;
DROP TABLE "C##SUVRES"."WORK_GROUP" cascade constraints;
DROP TABLE "C##SUVRES"."FACULTY" cascade constraints;
DROP TABLE "C##SUVRES"."EMPLOYEE" cascade constraints;
DROP TABLE "C##SUVRES"."SUBJECT" cascade constraints;
DROP TABLE "C##SUVRES"."WORK_GROUP" cascade constraints;
DROP TABLE "C##SUVRES"."CATHEDRAL" cascade constraints;
DROP TABLE "C##SUVRES"."POSITION" cascade constraints;
DROP TABLE "C##SUVRES"."CLASSES" cascade constraints;
DROP TABLE "C##SUVRES"."STUDENT" cascade constraints;
DROP TABLE "C##SUVRES"."MARK" cascade constraints;
DROP TABLE "C##SUVRES"."STUDENT_WORK_GROUP" cascade constraints;
--------------------------------------------------------
--  DDL for Table CATHEDRAL
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."CATHEDRAL" 
   (	"ID" NUMBER(10,0), 
	"CATHEDRAL_NAME" VARCHAR2(100 BYTE), 
	"FACULTY_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLASSES
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."CLASSES" 
   (	"ID" NUMBER(10,0), 
	"CLASSES_TYPE" VARCHAR2(40 BYTE), 
	"WORK_GROUP_ID" NUMBER(38,0), 
	"SUBJECT_ID" NUMBER(38,0), 
	"EMPLOYEE_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."EMPLOYEE" 
   (	"ID" NUMBER(10,0), 
	"FIRST_NAME" VARCHAR2(49 BYTE), 
	"LAST_NAME" VARCHAR2(40 BYTE), 
	"PESEL" VARCHAR2(11 BYTE), 
	"LOCALITY" VARCHAR2(50 BYTE), 
	"POSTAL_CODE" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(12 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"DATE_OF_EMPLOYMENT" DATE, 
	"DATE_OF_RELEASE" DATE, 
	"POSITION_ID" NUMBER(7,0), 
	"FACULTY_ID" NUMBER(38,0), 
	"CATHEDRAL_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACULTY
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."FACULTY" 
   (	"ID" NUMBER(10,0), 
	"FACULTY_NAME" VARCHAR2(200 BYTE), 
	"ABBREVIATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MARK
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."MARK" 
   (	"ID" NUMBER(38,0), 
	"MARK" NUMBER(4,1), 
	"CLASSES_ID" NUMBER(38,0), 
	"STUDENT_INDEX" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSITION
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."POSITION" 
   (	"ID" NUMBER(10,0), 
	"NAME_OF_POSITION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."STUDENT" 
   (	"index" NUMBER(10,0), 
	"FIRST_NAME" VARCHAR2(49 BYTE), 
	"LAST_NAME" VARCHAR2(40 BYTE), 
	"PESEL" VARCHAR2(11 BYTE), 
	"LOCALITY" VARCHAR2(50 BYTE), 
	"POSTAL_CODE" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(12 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"DATE_OF_ENROLLMENT" DATE, 
	"DATE_OF_DISCHARGE" DATE, 
	"FACULTY_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT_WORK_GROUP
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."STUDENT_WORK_GROUP" 
   (	"STUDENT_INDEX" NUMBER(38,0), 
	"WORK_GROUP_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBJECT
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."SUBJECT" 
   (	"ID" NUMBER(10,0), 
	"SUBJECT_NAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WORK_GROUP
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."WORK_GROUP" 
   (	"ID" NUMBER(10,0), 
	"GROUP_CODE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACULTY
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."FACULTY" 
   (	"ID" NUMBER(10,0), 
	"FACULTY_NAME" VARCHAR2(200 BYTE), 
	"ABBREVIATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."EMPLOYEE" 
   (	"ID" NUMBER(10,0), 
	"FIRST_NAME" VARCHAR2(49 BYTE), 
	"LAST_NAME" VARCHAR2(40 BYTE), 
	"PESEL" VARCHAR2(11 BYTE), 
	"LOCALITY" VARCHAR2(50 BYTE), 
	"POSTAL_CODE" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(12 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"DATE_OF_EMPLOYMENT" DATE, 
	"DATE_OF_RELEASE" DATE, 
	"POSITION_ID" NUMBER(7,0), 
	"FACULTY_ID" NUMBER(38,0), 
	"CATHEDRAL_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBJECT
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."SUBJECT" 
   (	"ID" NUMBER(10,0), 
	"SUBJECT_NAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WORK_GROUP
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."WORK_GROUP" 
   (	"ID" NUMBER(10,0), 
	"GROUP_CODE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATHEDRAL
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."CATHEDRAL" 
   (	"ID" NUMBER(10,0), 
	"CATHEDRAL_NAME" VARCHAR2(100 BYTE), 
	"FACULTY_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSITION
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."POSITION" 
   (	"ID" NUMBER(10,0), 
	"NAME_OF_POSITION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLASSES
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."CLASSES" 
   (	"ID" NUMBER(10,0), 
	"CLASSES_TYPE" VARCHAR2(40 BYTE), 
	"WORK_GROUP_ID" NUMBER(38,0), 
	"SUBJECT_ID" NUMBER(38,0), 
	"EMPLOYEE_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."STUDENT" 
   (	"index" NUMBER(10,0), 
	"FIRST_NAME" VARCHAR2(49 BYTE), 
	"LAST_NAME" VARCHAR2(40 BYTE), 
	"PESEL" VARCHAR2(11 BYTE), 
	"LOCALITY" VARCHAR2(50 BYTE), 
	"POSTAL_CODE" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(12 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"DATE_OF_ENROLLMENT" DATE, 
	"DATE_OF_DISCHARGE" DATE, 
	"FACULTY_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MARK
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."MARK" 
   (	"ID" NUMBER(38,0), 
	"MARK" NUMBER(4,1), 
	"CLASSES_ID" NUMBER(38,0), 
	"STUDENT_INDEX" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT_WORK_GROUP
--------------------------------------------------------

  CREATE TABLE "C##SUVRES"."STUDENT_WORK_GROUP" 
   (	"STUDENT_INDEX" NUMBER(38,0), 
	"WORK_GROUP_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##SUVRES.CATHEDRAL
SET DEFINE OFF;
Insert into C##SUVRES.CATHEDRAL (ID,CATHEDRAL_NAME,FACULTY_ID) values ('1','Katedra Informatyki Stosowanej i Modelowania','1');
Insert into C##SUVRES.CATHEDRAL (ID,CATHEDRAL_NAME,FACULTY_ID) values ('2','Katedra Techniki Cieplnej i Ochrony Środowiska','1');
REM INSERTING into C##SUVRES.CLASSES
SET DEFINE OFF;
Insert into C##SUVRES.CLASSES (ID,CLASSES_TYPE,WORK_GROUP_ID,SUBJECT_ID,EMPLOYEE_ID) values ('1','w','1','1','1');
Insert into C##SUVRES.CLASSES (ID,CLASSES_TYPE,WORK_GROUP_ID,SUBJECT_ID,EMPLOYEE_ID) values ('2','l','1','1','1');
Insert into C##SUVRES.CLASSES (ID,CLASSES_TYPE,WORK_GROUP_ID,SUBJECT_ID,EMPLOYEE_ID) values ('3','l','2','1','1');
Insert into C##SUVRES.CLASSES (ID,CLASSES_TYPE,WORK_GROUP_ID,SUBJECT_ID,EMPLOYEE_ID) values ('4','w','1','2','2');
Insert into C##SUVRES.CLASSES (ID,CLASSES_TYPE,WORK_GROUP_ID,SUBJECT_ID,EMPLOYEE_ID) values ('5','w','3','3','1');
REM INSERTING into C##SUVRES.EMPLOYEE
SET DEFINE OFF;
Insert into C##SUVRES.EMPLOYEE (ID,FIRST_NAME,LAST_NAME,PESEL,LOCALITY,POSTAL_CODE,PHONE,EMAIL,DATE_OF_EMPLOYMENT,DATE_OF_RELEASE,POSITION_ID,FACULTY_ID,CATHEDRAL_ID) values ('1','Tomasz','Lechłas','88876789890','Kraków','32-021','666555444','leclas@agh.pl',to_date('99/01/01','RR/MM/DD'),null,'2','1','1');
Insert into C##SUVRES.EMPLOYEE (ID,FIRST_NAME,LAST_NAME,PESEL,LOCALITY,POSTAL_CODE,PHONE,EMAIL,DATE_OF_EMPLOYMENT,DATE_OF_RELEASE,POSITION_ID,FACULTY_ID,CATHEDRAL_ID) values ('2','Jadwiga','Smolka','99887678769','Kraków','32-021','666533322','smolka@agh.pl',to_date('19/01/01','RR/MM/DD'),null,'3','1','2');
Insert into C##SUVRES.EMPLOYEE (ID,FIRST_NAME,LAST_NAME,PESEL,LOCALITY,POSTAL_CODE,PHONE,EMAIL,DATE_OF_EMPLOYMENT,DATE_OF_RELEASE,POSITION_ID,FACULTY_ID,CATHEDRAL_ID) values ('3','Mikołaj','Wiecławski','99887678765','Kraków','32-021','666533111','wiecha@agh.pl',to_date('71/01/01','RR/MM/DD'),to_date('18/01/01','RR/MM/DD'),'2','1','1');
REM INSERTING into C##SUVRES.FACULTY
SET DEFINE OFF;
Insert into C##SUVRES.FACULTY (ID,FACULTY_NAME,ABBREVIATION) values ('1','Wydział Inżynierii Metali i Informatyki Przemysłowej','WIMiIP');
Insert into C##SUVRES.FACULTY (ID,FACULTY_NAME,ABBREVIATION) values ('2','Wydział Informatyki, Eleketroniki i Telekomunikacji','WIET');
REM INSERTING into C##SUVRES.MARK
SET DEFINE OFF;
Insert into C##SUVRES.MARK (ID,MARK,CLASSES_ID,STUDENT_INDEX) values ('1','3,5','1','111111');
Insert into C##SUVRES.MARK (ID,MARK,CLASSES_ID,STUDENT_INDEX) values ('2','2,5','5','222222');
Insert into C##SUVRES.MARK (ID,MARK,CLASSES_ID,STUDENT_INDEX) values ('3','4,5','5','333333');
Insert into C##SUVRES.MARK (ID,MARK,CLASSES_ID,STUDENT_INDEX) values ('4','3,5','5','111111');
REM INSERTING into C##SUVRES.POSITION
SET DEFINE OFF;
Insert into C##SUVRES.POSITION (ID,NAME_OF_POSITION) values ('1','sekretarz');
Insert into C##SUVRES.POSITION (ID,NAME_OF_POSITION) values ('2','wykładowca');
Insert into C##SUVRES.POSITION (ID,NAME_OF_POSITION) values ('3','doktorant');
REM INSERTING into C##SUVRES.STUDENT
SET DEFINE OFF;
Insert into C##SUVRES.STUDENT ("index",FIRST_NAME,LAST_NAME,PESEL,LOCALITY,POSTAL_CODE,PHONE,EMAIL,DATE_OF_ENROLLMENT,DATE_OF_DISCHARGE,FACULTY_ID) values ('111111','Arkadiusz','Wichurka','8887678999','Kraków','32-021','666555422','wichurka@student.agh.pl',to_date('20/10/01','RR/MM/DD'),null,'1');
Insert into C##SUVRES.STUDENT ("index",FIRST_NAME,LAST_NAME,PESEL,LOCALITY,POSTAL_CODE,PHONE,EMAIL,DATE_OF_ENROLLMENT,DATE_OF_DISCHARGE,FACULTY_ID) values ('222222','Mariusz','Kałabunga','8887678922','Kraków','32-021','663355422','kałabunga@student.agh.pl',to_date('19/10/01','RR/MM/DD'),to_date('20/10/01','RR/MM/DD'),'1');
Insert into C##SUVRES.STUDENT ("index",FIRST_NAME,LAST_NAME,PESEL,LOCALITY,POSTAL_CODE,PHONE,EMAIL,DATE_OF_ENROLLMENT,DATE_OF_DISCHARGE,FACULTY_ID) values ('333333','Izebedeusz','Palestizra','8887678910','Kraków','32-021','223355422','palestr@student.agh.pl',to_date('10/10/01','RR/MM/DD'),null,'1');
REM INSERTING into C##SUVRES.STUDENT_WORK_GROUP
SET DEFINE OFF;
Insert into C##SUVRES.STUDENT_WORK_GROUP (STUDENT_INDEX,WORK_GROUP_ID) values ('111111','3');
Insert into C##SUVRES.STUDENT_WORK_GROUP (STUDENT_INDEX,WORK_GROUP_ID) values ('222222','2');
Insert into C##SUVRES.STUDENT_WORK_GROUP (STUDENT_INDEX,WORK_GROUP_ID) values ('222222','3');
Insert into C##SUVRES.STUDENT_WORK_GROUP (STUDENT_INDEX,WORK_GROUP_ID) values ('333333','1');
REM INSERTING into C##SUVRES.SUBJECT
SET DEFINE OFF;
Insert into C##SUVRES.SUBJECT (ID,SUBJECT_NAME) values ('1','podstawy mechaniki ciała stałego');
Insert into C##SUVRES.SUBJECT (ID,SUBJECT_NAME) values ('2','metody numeryczne');
Insert into C##SUVRES.SUBJECT (ID,SUBJECT_NAME) values ('3','bazy danych');
REM INSERTING into C##SUVRES.WORK_GROUP
SET DEFINE OFF;
Insert into C##SUVRES.WORK_GROUP (ID,GROUP_CODE) values ('1','g1_it_2020');
Insert into C##SUVRES.WORK_GROUP (ID,GROUP_CODE) values ('2','g2_it_2020');
Insert into C##SUVRES.WORK_GROUP (ID,GROUP_CODE) values ('3','g3_it_2020');
--------------------------------------------------------
--  DDL for Index CATHEDRAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SUVRES"."CATHEDRAL_PK" ON "C##SUVRES"."CATHEDRAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLASSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SUVRES"."CLASSES_PK" ON "C##SUVRES"."CLASSES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SUVRES"."EMPLOYEE_PK" ON "C##SUVRES"."EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FACULTY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SUVRES"."FACULTY_PK" ON "C##SUVRES"."FACULTY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MARK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SUVRES"."MARK_PK" ON "C##SUVRES"."MARK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POSITION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SUVRES"."POSITION_PK" ON "C##SUVRES"."POSITION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SUVRES"."STUDENT_PK" ON "C##SUVRES"."STUDENT" ("index") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENT_WORK_GROUP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SUVRES"."STUDENT_WORK_GROUP_PK" ON "C##SUVRES"."STUDENT_WORK_GROUP" ("STUDENT_INDEX", "WORK_GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBJECT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SUVRES"."SUBJECT_PK" ON "C##SUVRES"."SUBJECT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WORK_GROUP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SUVRES"."WORK_GROUP_PK" ON "C##SUVRES"."WORK_GROUP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CATHEDRAL
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."CATHEDRAL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."CATHEDRAL" MODIFY ("FACULTY_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."CATHEDRAL" ADD CONSTRAINT "CATHEDRAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLASSES
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."CLASSES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."CLASSES" MODIFY ("WORK_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."CLASSES" MODIFY ("SUBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."CLASSES" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."CLASSES" ADD CONSTRAINT "CLASSES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."EMPLOYEE" MODIFY ("POSITION_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."EMPLOYEE" MODIFY ("FACULTY_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACULTY
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."FACULTY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."FACULTY" ADD CONSTRAINT "FACULTY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MARK
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."MARK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."MARK" MODIFY ("CLASSES_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."MARK" MODIFY ("STUDENT_INDEX" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."MARK" ADD CONSTRAINT "MARK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POSITION
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."POSITION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."POSITION" ADD CONSTRAINT "POSITION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."STUDENT" MODIFY ("index" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."STUDENT" MODIFY ("FACULTY_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("index")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT_WORK_GROUP
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."STUDENT_WORK_GROUP" MODIFY ("STUDENT_INDEX" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."STUDENT_WORK_GROUP" MODIFY ("WORK_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."STUDENT_WORK_GROUP" ADD CONSTRAINT "STUDENT_WORK_GROUP_PK" PRIMARY KEY ("STUDENT_INDEX", "WORK_GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBJECT
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."SUBJECT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."SUBJECT" ADD CONSTRAINT "SUBJECT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORK_GROUP
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."WORK_GROUP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##SUVRES"."WORK_GROUP" ADD CONSTRAINT "WORK_GROUP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATHEDRAL
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."CATHEDRAL" ADD CONSTRAINT "CATHEDRAL_FACULTY_FK" FOREIGN KEY ("FACULTY_ID")
	  REFERENCES "C##SUVRES"."FACULTY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLASSES
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."CLASSES" ADD CONSTRAINT "CLASSES_EMPLOYEE_FK" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "C##SUVRES"."EMPLOYEE" ("ID") ENABLE;
  ALTER TABLE "C##SUVRES"."CLASSES" ADD CONSTRAINT "CLASSES_SUBJECT_FK" FOREIGN KEY ("SUBJECT_ID")
	  REFERENCES "C##SUVRES"."SUBJECT" ("ID") ENABLE;
  ALTER TABLE "C##SUVRES"."CLASSES" ADD CONSTRAINT "CLASSES_WORK_GROUP_FK" FOREIGN KEY ("WORK_GROUP_ID")
	  REFERENCES "C##SUVRES"."WORK_GROUP" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_CATHEDRAL_FK" FOREIGN KEY ("CATHEDRAL_ID")
	  REFERENCES "C##SUVRES"."CATHEDRAL" ("ID") ENABLE;
  ALTER TABLE "C##SUVRES"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_FACULTY_FK" FOREIGN KEY ("FACULTY_ID")
	  REFERENCES "C##SUVRES"."FACULTY" ("ID") ENABLE;
  ALTER TABLE "C##SUVRES"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_POSITION_FK" FOREIGN KEY ("POSITION_ID")
	  REFERENCES "C##SUVRES"."POSITION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MARK
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."MARK" ADD CONSTRAINT "MARK_CLASSES_FK" FOREIGN KEY ("CLASSES_ID")
	  REFERENCES "C##SUVRES"."CLASSES" ("ID") ENABLE;
  ALTER TABLE "C##SUVRES"."MARK" ADD CONSTRAINT "MARK_STUDENT_FK" FOREIGN KEY ("STUDENT_INDEX")
	  REFERENCES "C##SUVRES"."STUDENT" ("index") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."STUDENT" ADD CONSTRAINT "STUDENT_FACULTY_FK" FOREIGN KEY ("FACULTY_ID")
	  REFERENCES "C##SUVRES"."FACULTY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT_WORK_GROUP
--------------------------------------------------------

  ALTER TABLE "C##SUVRES"."STUDENT_WORK_GROUP" ADD CONSTRAINT "STUDENT_WORK_GROUP_STUDENT_FK" FOREIGN KEY ("STUDENT_INDEX")
	  REFERENCES "C##SUVRES"."STUDENT" ("index") ENABLE;
  ALTER TABLE "C##SUVRES"."STUDENT_WORK_GROUP" ADD CONSTRAINT "STUDENT_WORK_GROUP_FK" FOREIGN KEY ("WORK_GROUP_ID")
	  REFERENCES "C##SUVRES"."WORK_GROUP" ("ID") ENABLE;
